FROM node:19.1.0-slim

WORKDIR /app

COPY ./app/package.json ./package.json

ARG ACCOUNT_DB_HOST
ENV ACCOUNT_DB_HOST ${ACCOUNT_DB_HOST}

ARG ACCOUNT_DB_PORT
ENV ACCOUNT_DB_PORT ${ACCOUNT_DB_PORT}

ARG ACCOUNT_DB_NAME
ENV ACCOUNT_DB_NAME ${ACCOUNT_DB_NAME}

ARG ACCOUNT_DB_USERNAME
ENV ACCOUNT_DB_USERNAME ${ACCOUNT_DB_USERNAME}

ARG ACCOUNT_DB_PASSWORD
ENV ACCOUNT_DB_PASSWORD ${ACCOUNT_DB_PASSWORD}

RUN npm install

CMD npm run start:dev